/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as MfaVerifyRouteImport } from './routes/mfa-verify'
import { Route as MfaRecoveryRouteImport } from './routes/mfa-recovery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BasecontrolRouteImport } from './routes/basecontrol'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as RegisterAdminRouteImport } from './routes/register.admin'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as AuthenticatedEocRouteImport } from './routes/_authenticated/eoc'
import { Route as ApiPublicRetentionPurgeRouteImport } from './routes/api/public/retention-purge'
import { Route as AuthenticatedResponderDashboardRouteImport } from './routes/_authenticated/responder.dashboard'
import { Route as AuthenticatedGbvDashboardRouteImport } from './routes/_authenticated/gbv.dashboard'
import { Route as AuthenticatedDeveloperDashboardRouteImport } from './routes/_authenticated/developer.dashboard'
import { Route as AuthenticatedCounsellorDashboardRouteImport } from './routes/_authenticated/counsellor.dashboard'
import { Route as AuthenticatedAdminRetentionRouteImport } from './routes/_authenticated/admin.retention'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account.security'
import { Route as AuthenticatedAdminReportsIdRouteImport } from './routes/_authenticated/admin.reports.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaVerifyRoute = MfaVerifyRouteImport.update({
  id: '/mfa-verify',
  path: '/mfa-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRecoveryRoute = MfaRecoveryRouteImport.update({
  id: '/mfa-recovery',
  path: '/mfa-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BasecontrolRoute = BasecontrolRouteImport.update({
  id: '/basecontrol',
  path: '/basecontrol',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAdminRoute = RegisterAdminRouteImport.update({
  id: '/register/admin',
  path: '/register/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEocRoute = AuthenticatedEocRouteImport.update({
  id: '/eoc',
  path: '/eoc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRetentionPurgeRoute = ApiPublicRetentionPurgeRouteImport.update({
  id: '/api/public/retention-purge',
  path: '/api/public/retention-purge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResponderDashboardRoute =
  AuthenticatedResponderDashboardRouteImport.update({
    id: '/responder/dashboard',
    path: '/responder/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGbvDashboardRoute =
  AuthenticatedGbvDashboardRouteImport.update({
    id: '/gbv/dashboard',
    path: '/gbv/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperDashboardRoute =
  AuthenticatedDeveloperDashboardRouteImport.update({
    id: '/developer/dashboard',
    path: '/developer/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCounsellorDashboardRoute =
  AuthenticatedCounsellorDashboardRouteImport.update({
    id: '/counsellor/dashboard',
    path: '/counsellor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRetentionRoute =
  AuthenticatedAdminRetentionRouteImport.update({
    id: '/admin/retention',
    path: '/admin/retention',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsIdRoute =
  AuthenticatedAdminReportsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminReportsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/basecontrol': typeof BasecontrolRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/mfa-recovery': typeof MfaRecoveryRoute
  '/mfa-verify': typeof MfaVerifyRoute
  '/pending': typeof PendingRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
  '/eoc': typeof AuthenticatedEocRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/register/admin': typeof RegisterAdminRoute
  '/learn/': typeof LearnIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRouteWithChildren
  '/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/counsellor/dashboard': typeof AuthenticatedCounsellorDashboardRoute
  '/developer/dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/gbv/dashboard': typeof AuthenticatedGbvDashboardRoute
  '/responder/dashboard': typeof AuthenticatedResponderDashboardRoute
  '/api/public/retention-purge': typeof ApiPublicRetentionPurgeRoute
  '/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/basecontrol': typeof BasecontrolRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/mfa-recovery': typeof MfaRecoveryRoute
  '/mfa-verify': typeof MfaVerifyRoute
  '/pending': typeof PendingRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
  '/eoc': typeof AuthenticatedEocRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/register/admin': typeof RegisterAdminRoute
  '/learn': typeof LearnIndexRoute
  '/register': typeof RegisterIndexRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRouteWithChildren
  '/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/counsellor/dashboard': typeof AuthenticatedCounsellorDashboardRoute
  '/developer/dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/gbv/dashboard': typeof AuthenticatedGbvDashboardRoute
  '/responder/dashboard': typeof AuthenticatedResponderDashboardRoute
  '/api/public/retention-purge': typeof ApiPublicRetentionPurgeRoute
  '/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/basecontrol': typeof BasecontrolRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/mfa-recovery': typeof MfaRecoveryRoute
  '/mfa-verify': typeof MfaVerifyRoute
  '/pending': typeof PendingRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRoute
  '/_authenticated/eoc': typeof AuthenticatedEocRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/register/admin': typeof RegisterAdminRoute
  '/learn/': typeof LearnIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_authenticated/account/security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRouteWithChildren
  '/_authenticated/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/_authenticated/counsellor/dashboard': typeof AuthenticatedCounsellorDashboardRoute
  '/_authenticated/developer/dashboard': typeof AuthenticatedDeveloperDashboardRoute
  '/_authenticated/gbv/dashboard': typeof AuthenticatedGbvDashboardRoute
  '/_authenticated/responder/dashboard': typeof AuthenticatedResponderDashboardRoute
  '/api/public/retention-purge': typeof ApiPublicRetentionPurgeRoute
  '/_authenticated/admin/reports/$id': typeof AuthenticatedAdminReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/basecontrol'
    | '/dashboard'
    | '/emergency'
    | '/feedback'
    | '/login'
    | '/mfa-recovery'
    | '/mfa-verify'
    | '/pending'
    | '/report'
    | '/services'
    | '/eoc'
    | '/learn/$slug'
    | '/register/admin'
    | '/learn/'
    | '/register/'
    | '/account/security'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/retention'
    | '/counsellor/dashboard'
    | '/developer/dashboard'
    | '/gbv/dashboard'
    | '/responder/dashboard'
    | '/api/public/retention-purge'
    | '/admin/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/basecontrol'
    | '/dashboard'
    | '/emergency'
    | '/feedback'
    | '/login'
    | '/mfa-recovery'
    | '/mfa-verify'
    | '/pending'
    | '/report'
    | '/services'
    | '/eoc'
    | '/learn/$slug'
    | '/register/admin'
    | '/learn'
    | '/register'
    | '/account/security'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/retention'
    | '/counsellor/dashboard'
    | '/developer/dashboard'
    | '/gbv/dashboard'
    | '/responder/dashboard'
    | '/api/public/retention-purge'
    | '/admin/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/basecontrol'
    | '/dashboard'
    | '/emergency'
    | '/feedback'
    | '/login'
    | '/mfa-recovery'
    | '/mfa-verify'
    | '/pending'
    | '/report'
    | '/services'
    | '/_authenticated/eoc'
    | '/learn/$slug'
    | '/register/admin'
    | '/learn/'
    | '/register/'
    | '/_authenticated/account/security'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/retention'
    | '/_authenticated/counsellor/dashboard'
    | '/_authenticated/developer/dashboard'
    | '/_authenticated/gbv/dashboard'
    | '/_authenticated/responder/dashboard'
    | '/api/public/retention-purge'
    | '/_authenticated/admin/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BasecontrolRoute: typeof BasecontrolRoute
  DashboardRoute: typeof DashboardRoute
  EmergencyRoute: typeof EmergencyRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  MfaRecoveryRoute: typeof MfaRecoveryRoute
  MfaVerifyRoute: typeof MfaVerifyRoute
  PendingRoute: typeof PendingRoute
  ReportRoute: typeof ReportRoute
  ServicesRoute: typeof ServicesRoute
  LearnSlugRoute: typeof LearnSlugRoute
  RegisterAdminRoute: typeof RegisterAdminRoute
  LearnIndexRoute: typeof LearnIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ApiPublicRetentionPurgeRoute: typeof ApiPublicRetentionPurgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-verify': {
      id: '/mfa-verify'
      path: '/mfa-verify'
      fullPath: '/mfa-verify'
      preLoaderRoute: typeof MfaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-recovery': {
      id: '/mfa-recovery'
      path: '/mfa-recovery'
      fullPath: '/mfa-recovery'
      preLoaderRoute: typeof MfaRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basecontrol': {
      id: '/basecontrol'
      path: '/basecontrol'
      fullPath: '/basecontrol'
      preLoaderRoute: typeof BasecontrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/admin': {
      id: '/register/admin'
      path: '/register/admin'
      fullPath: '/register/admin'
      preLoaderRoute: typeof RegisterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/eoc': {
      id: '/_authenticated/eoc'
      path: '/eoc'
      fullPath: '/eoc'
      preLoaderRoute: typeof AuthenticatedEocRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/retention-purge': {
      id: '/api/public/retention-purge'
      path: '/api/public/retention-purge'
      fullPath: '/api/public/retention-purge'
      preLoaderRoute: typeof ApiPublicRetentionPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/responder/dashboard': {
      id: '/_authenticated/responder/dashboard'
      path: '/responder/dashboard'
      fullPath: '/responder/dashboard'
      preLoaderRoute: typeof AuthenticatedResponderDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gbv/dashboard': {
      id: '/_authenticated/gbv/dashboard'
      path: '/gbv/dashboard'
      fullPath: '/gbv/dashboard'
      preLoaderRoute: typeof AuthenticatedGbvDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/dashboard': {
      id: '/_authenticated/developer/dashboard'
      path: '/developer/dashboard'
      fullPath: '/developer/dashboard'
      preLoaderRoute: typeof AuthenticatedDeveloperDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counsellor/dashboard': {
      id: '/_authenticated/counsellor/dashboard'
      path: '/counsellor/dashboard'
      fullPath: '/counsellor/dashboard'
      preLoaderRoute: typeof AuthenticatedCounsellorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/retention': {
      id: '/_authenticated/admin/retention'
      path: '/admin/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AuthenticatedAdminRetentionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/security': {
      id: '/_authenticated/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports/$id': {
      id: '/_authenticated/admin/reports/$id'
      path: '/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AuthenticatedAdminReportsIdRouteImport
      parentRoute: typeof AuthenticatedAdminReportsRoute
    }
  }
}

interface AuthenticatedAdminReportsRouteChildren {
  AuthenticatedAdminReportsIdRoute: typeof AuthenticatedAdminReportsIdRoute
}

const AuthenticatedAdminReportsRouteChildren: AuthenticatedAdminReportsRouteChildren =
  {
    AuthenticatedAdminReportsIdRoute: AuthenticatedAdminReportsIdRoute,
  }

const AuthenticatedAdminReportsRouteWithChildren =
  AuthenticatedAdminReportsRoute._addFileChildren(
    AuthenticatedAdminReportsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEocRoute: typeof AuthenticatedEocRoute
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRouteWithChildren
  AuthenticatedAdminRetentionRoute: typeof AuthenticatedAdminRetentionRoute
  AuthenticatedCounsellorDashboardRoute: typeof AuthenticatedCounsellorDashboardRoute
  AuthenticatedDeveloperDashboardRoute: typeof AuthenticatedDeveloperDashboardRoute
  AuthenticatedGbvDashboardRoute: typeof AuthenticatedGbvDashboardRoute
  AuthenticatedResponderDashboardRoute: typeof AuthenticatedResponderDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEocRoute: AuthenticatedEocRoute,
  AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRouteWithChildren,
  AuthenticatedAdminRetentionRoute: AuthenticatedAdminRetentionRoute,
  AuthenticatedCounsellorDashboardRoute: AuthenticatedCounsellorDashboardRoute,
  AuthenticatedDeveloperDashboardRoute: AuthenticatedDeveloperDashboardRoute,
  AuthenticatedGbvDashboardRoute: AuthenticatedGbvDashboardRoute,
  AuthenticatedResponderDashboardRoute: AuthenticatedResponderDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BasecontrolRoute: BasecontrolRoute,
  DashboardRoute: DashboardRoute,
  EmergencyRoute: EmergencyRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  MfaRecoveryRoute: MfaRecoveryRoute,
  MfaVerifyRoute: MfaVerifyRoute,
  PendingRoute: PendingRoute,
  ReportRoute: ReportRoute,
  ServicesRoute: ServicesRoute,
  LearnSlugRoute: LearnSlugRoute,
  RegisterAdminRoute: RegisterAdminRoute,
  LearnIndexRoute: LearnIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ApiPublicRetentionPurgeRoute: ApiPublicRetentionPurgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
